# Generated by Django 4.2.7 on 2023-12-11 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 3, 31, 6, 114965, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=datetime.datetime(2023, 12, 11, 3, 31, 11, 868538, tzinfo=datetime.timezone.utc), upload_to='media/Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 3, 31, 14, 477323, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 12, 11, 3, 31, 19, 880057, tzinfo=datetime.timezone.utc), editable=False, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
